#group by 활용 

SELECT CART_ID AS 아이디
FROM CART_PRODUCTS 
WHERE NAME IN ('Milk', 'Yogurt')
GROUP BY CART_ID
    HAVING COUNT(DISTINCT NAME) >= 2 
ORDER BY 아이디 ASC ;

#Alias 이용
SELECT A.CART_ID AS 아이디
FROM CART_PRODUCTS AS A, CART_PRODUCTS B
WHERE A.NAME LIKE 'Milk' 
    AND B.NAME LIKE 'Yogurt'
    AND A.CART_ID = B.CART_ID
ORDER BY 아이디 ASC ;

#서브쿼리
SELECT A.CART_ID AS 아이디
FROM CART_PRODUCTS AS A
WHERE A.NAME LIKE 'Milk' 
    AND A.CART_ID IN (
    SELECT B.CART_ID 
        FROM CART_PRODUCTS AS B
        WHERE B.NAME LIKE 'Yogurt'
    ) 
ORDER BY 아이디 ASC ;
