#입양(B)에서 중성화 체크, 보호(A)에서는 중성화안됨


SELECT B.ANIMAL_ID AS ID, B.ANIMAL_TYPE AS TYPE, B.NAME AS 이름
FROM ANIMAL_OUTS B 
    INNER JOIN ANIMAL_INS A
    ON A.ANIMAL_ID = B.ANIMAL_ID 
WHERE A.SEX_UPON_INTAKE LIKE '%Intact%' 
    #AND B.SEX_UPON_OUTCOME IN ('%Spayed%', '%Neutered%')
    AND B.SEX_UPON_OUTCOME NOT LIKE '%Intact%' 
ORDER BY ID ASC ;
