#조인이용 => LEFT JOIN 은 왼쪽 테이블 기준으로 NULL값도 함께 출력할수있다. 

SELECT B.ANIMAL_ID AS ID , B.NAME AS 이름 
FROM ANIMAL_OUTS B 
    LEFT OUTER JOIN ANIMAL_INS A 
    ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE A.ANIMAL_ID IS NULL 
ORDER BY B.ANIMAL_ID ASC ; 


#1차시도(조인X)
SELECT DISTINCT B.ANIMAL_ID AS ID,  B.NAME AS 이름
FROM ANIMAL_INS A, ANIMAL_OUTS B
WHERE A.ANIMAL_ID != B.ANIMAL_ID AND A.NAME != B.NAME 
ORDER BY ID ASC ;

