#상위 3개 출력 => LIMIT 활용(ORDER BY에서)
#보호시작일은 존재하나(A), 입양시작일이 존재X(B) 

SELECT A.NAME AS 이름, A.DATETIME AS 보호시작일 
FROM ANIMAL_INS A 
    LEFT OUTER JOIN ANIMAL_OUTS B 
    ON A.ANIMAL_ID = B.ANIMAL_ID 
WHERE B.ANIMAL_ID IS NULL 
ORDER BY A.DATETIME ASC LIMIT 3 ;
