#입양일(OUTS.DATETIME)이 시작일(INS.DATETIME)보다 빠를 때 
#즉, OUT.DATETIME 숫자가 더 작아야함..!

SELECT A.ANIMAL_ID AS ID , A.NAME AS 이름
FROM ANIMAL_INS A 
    LEFT OUTER JOIN ANIMAL_OUTS B
    ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE B.DATETIME < A.DATETIME
ORDER BY A.DATETIME ASC 

