#변수설정해서 풀어야하는문제..ㄷㄷ

SET @HOUR = -1;

SELECT 
    (@HOUR := @HOUR +1) AS HOUR,
    (SELECT COUNT(*) 
     FROM ANIMAL_OUTS 
     WHERE HOUR(DATETIME) = @HOUR ) AS COUNT
FROM ANIMAL_OUTS 
WHERE @HOUR < 23



#1차시도
SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT
FROM ANIMAL_OUTS
WHERE HOUR(DATETIME) >= 0 AND HOUR(DATETIME) <= 23
GROUP BY HOUR(DATETIME)
ORDER BY HOUR(DATETIME)

